function createfigure(X1, YMatrix1, YMatrix2, YMatrix3)
%CREATEFIGURE(X1, YMATRIX1, YMATRIX2, YMATRIX3)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data
%  YMATRIX2:  matrix of y data
%  YMATRIX3:  matrix of y data

%  Auto-generated by MATLAB on 08-Sep-2018 22:27:20

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.0348958333333333 0.708333333333333 0.953125 0.254273504273505]);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',axes1);
set(plot1(1),'DisplayName','Raw data points','MarkerSize',5,'Marker','*',...
    'LineStyle','none');
set(plot1(2),'DisplayName','Non-linear fit','LineWidth',2);

% Create xlabel
xlabel('x_i');

% Create title
title('A plot');

% Create ylabel
ylabel('y_i');

box(axes1,'on');
% Create legend
legend(axes1,'show');

% Create axes
axes2 = axes('Parent',figure1,...
    'Position',[0.0354166666666667 0.409188034188034 0.950520833333333 0.226495726495726]);
hold(axes2,'on');

% Create multiple lines using matrix input to plot
plot2 = plot(X1,YMatrix2,'Parent',axes2);
set(plot2(1),'DisplayName','Raw data points','MarkerSize',5,'Marker','*',...
    'LineStyle','none');
set(plot2(2),'DisplayName','Non-linear fit','LineWidth',2);

% Create xlabel
xlabel('x_i');

% Create title
title('B plot');

% Create ylabel
ylabel('y_i');

box(axes2,'on');
% Create legend
legend(axes2,'show');

% Create axes
axes3 = axes('Parent',figure1,...
    'Position',[0.0395833333333333 0.0673076923076923 0.944270833333334 0.253205128205128]);
hold(axes3,'on');

% Create multiple lines using matrix input to plot
plot3 = plot(X1,YMatrix3,'Parent',axes3);
set(plot3(1),'DisplayName','Raw data points','MarkerSize',5,'Marker','*',...
    'LineStyle','none');
set(plot3(2),'DisplayName','Non-linear fit','LineWidth',2);

% Create xlabel
xlabel('x_i');

% Create title
title('C plot');

% Create ylabel
ylabel('y_i');

box(axes3,'on');
% Create legend
legend(axes3,'show');

